version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: files
    ports:
      - "5432:5432"

#  minio:
#    image: minio/minio
#    container_name: minio
#    command: server /data --console-address ":9001"
#    environment:
#      MINIO_ROOT_USER: minio
#      MINIO_ROOT_PASSWORD: minio123
#    ports:
#      - "9000:9000"
#      - "9001:9001"
